const $ = s => document.querySelector(s), $$ = s => [...document.querySelectorAll(s)];
const today = new Date(); today.setHours(0,0,0,0);
const iso = d => { const x=new Date(d); x.setMinutes(x.getMinutes()-x.getTimezoneOffset()); return x.toISOString().slice(0,10) };
const localDate = d => new Date(d+'T00:00:00');
const defaultTasks = [
  {id:'a1',title:'Finish math problem set',notes:'Chapter 6: questions 1–18',date:iso(today),time:'10:00',priority:'High',category:'School',estimate:90,done:false},
  {id:'a2',title:'Review psychology notes',notes:'Memory & learning lecture',date:iso(today),time:'14:00',priority:'Medium',category:'School',estimate:45,done:false},
  {id:'a3',title:'Submit programming assignment',notes:'Final project milestone',date:iso(new Date(+today+86400000)),time:'23:59',priority:'High',category:'School',estimate:120,done:false},
  {id:'a4',title:'History essay outline',notes:'Outline and source list',date:iso(new Date(+today+2*86400000)),time:'17:00',priority:'High',category:'School',estimate:60,done:false},
  {id:'a5',title:'Call Mom',notes:'',date:iso(new Date(+today+2*86400000)),time:'18:30',priority:'Low',category:'Personal',estimate:30,done:false},
  {id:'a6',title:'Read 30 pages',notes:'Cognitive science textbook',date:iso(new Date(+today-86400000)),time:'',priority:'Medium',category:'School',estimate:45,done:false},
  {id:'a7',title:'Organize class notes',notes:'',date:iso(new Date(+today-2*86400000)),time:'',priority:'Low',category:'School',estimate:30,done:true}
];
let tasks = JSON.parse(localStorage.getItem('focusflow-tasks')||'null') || defaultTasks;
let selectedDate=iso(today), displayDate=new Date(today), calMode='month';
function save(){localStorage.setItem('focusflow-tasks',JSON.stringify(tasks))}
function fmtDate(date, short=false){return localDate(date).toLocaleDateString(undefined,{month:short?'short':'long',day:'numeric'})}
function formatTime(t){if(!t)return 'Any time'; const [h,m]=t.split(':');return new Date(2000,0,1,h,m).toLocaleTimeString([],{hour:'numeric',minute:'2-digit'})}
function daysAway(d){return Math.round((localDate(d)-today)/86400000)}
function empty(text){return `<div class="empty">${text}</div>`}
function taskHTML(t,table=false){if(table)return `<div class="table-row"><div class="table-task"><input class="check" type="checkbox" ${t.done?'checked':''} data-toggle="${t.id}"><strong>${t.title}</strong></div><span>${fmtDate(t.date,true)}${t.time?' · '+formatTime(t.time):''}</span><span class="pill ${t.priority}">${t.priority}</span><span class="category">${t.category}</span><button class="delete-btn" data-delete="${t.id}">×</button></div>`;return `<div class="task-row ${t.done?'done':''}" draggable="true" data-drag="${t.id}"><input class="check" type="checkbox" ${t.done?'checked':''} data-toggle="${t.id}"><div class="task-copy"><strong>${t.title}</strong><small>${t.time?formatTime(t.time)+' · ':''}${t.notes||t.category}</small></div><span class="pill ${t.priority}">${t.priority}</span></div>`}
function renderDashboard(){let active=tasks.filter(t=>!t.done), due=active.filter(t=>t.date===iso(today)), over=active.filter(t=>daysAway(t.date)<0), up=active.filter(t=>daysAway(t.date)>0&&daysAway(t.date)<=7), completed=tasks.filter(t=>t.done);$('#dueTodayStat').textContent=due.length;$('#dueTodaySub').textContent=due.length?`${due.reduce((s,t)=>s+t.estimate,0)/60} hours planned`:'Nothing scheduled';$('#upcomingStat').textContent=up.length;$('#overdueStat').textContent=over.length;$('#overdueSub').textContent=over.length?'Needs attention':'You’re on track';$('#completedStat').textContent=completed.length;$('#todayTasks').innerHTML=due.length?due.sort(sortTime).map(taskHTML).join(''):empty('Your day is clear. Add a task to get started.');let all=tasks.filter(t=>t.date===iso(today)), pct=all.length?Math.round(all.filter(t=>t.done).length/all.length*100):0;$('#progressPercent').textContent=pct+'%';$('#progressRing').style.setProperty('--p',pct);$('#progressBar').style.width=pct+'%';$('#dailyGoalText').textContent=`${all.filter(t=>t.done).length} of ${all.length} tasks`;$('#progressCopy').textContent=pct===100&&all.length?'You did it!':'One task at a time';$('#progressDetail').textContent=all.length?`${all.filter(t=>!t.done).length} task${all.filter(t=>!t.done).length===1?'':'s'} left for today.`:'Add a task to plan your day.';let deadlines=active.filter(t=>daysAway(t.date)>=0).sort(sortDate).slice(0,4);$('#deadlineList').innerHTML=deadlines.length?deadlines.map(deadlineHTML).join(''):empty('No upcoming deadlines.');renderChart()}
function deadlineHTML(t){let d=localDate(t.date);return `<div class="deadline"><div class="date-block"><b>${d.getDate()}</b><small>${d.toLocaleDateString(undefined,{month:'short'})}</small></div><div class="deadline-copy"><strong>${t.title}</strong><span>${daysLabel(t.date)}${t.time?' · '+formatTime(t.time):''}</span></div><span class="pill ${t.priority}">${t.priority}</span></div>`}
function sortDate(a,b){return a.date.localeCompare(b.date)||(a.time||'99').localeCompare(b.time||'99')}function sortTime(a,b){return (a.time||'99').localeCompare(b.time||'99')}
function daysLabel(d){let n=daysAway(d);return n===0?'Due today':n===1?'Due tomorrow':n<0?`${-n} day${n===-1?'':'s'} overdue`:`Due in ${n} days`}
function renderChart(){let start=new Date(today);start.setDate(today.getDate()-today.getDay()+1);let total=0,html='';for(let i=0;i<7;i++){let d=iso(new Date(+start+i*86400000)),hrs=tasks.filter(t=>t.date===d&&!t.done).reduce((s,t)=>s+t.estimate,0)/60;total+=hrs;html+=`<div class="chart-col ${d===iso(today)?'today':''}"><i style="height:${Math.max(4,Math.min(100,hrs*28))}px"></i><span>${new Date(+start+i*86400000).toLocaleDateString(undefined,{weekday:'narrow'})}</span></div>`}$('#workloadChart').innerHTML=html;$('#workloadTotal').textContent=`${total%1?total.toFixed(1):total}h total`}
function renderTasks(){let q=$('#taskSearch').value.toLowerCase(),p=$('#priorityFilter').value,c=$('#categoryFilter').value,s=$('#statusFilter').value;let list=tasks.filter(t=>(s==='all'||s==='done'?t.done:!t.done)&&(p==='all'||t.priority===p)&&(c==='all'||t.category===c)&&(`${t.title} ${t.notes}`).toLowerCase().includes(q)).sort(sortDate);$('#allTasksList').innerHTML=list.length?list.map(t=>taskHTML(t,true)).join(''):empty('No tasks match these filters.');$('#taskNavCount').textContent=tasks.filter(t=>!t.done).length;$('#todayNavCount').textContent=tasks.filter(t=>!t.done&&t.date===iso(today)).length}
function renderToday(){let list=tasks.filter(t=>t.date===iso(today)).sort(sortTime), active=list.filter(t=>!t.done), mins=list.reduce((s,t)=>s+t.estimate,0);$('#todayViewDate').textContent=today.toLocaleDateString(undefined,{weekday:'long',month:'long',day:'numeric'}).toUpperCase();$('#todayTaskCount').textContent=`${list.length} task${list.length===1?'':'s'} planned`;$('#todayHours').textContent=`${Math.floor(mins/60)}h ${mins%60}m`;$('#todayDone').textContent=`${list.filter(t=>t.done).length} / ${list.length}`;let slots=['09:00','11:00','14:00','16:00','19:00'];$('#todayTimeline').innerHTML=slots.map((slot,i)=>{let t=active.find(x=>x.time===slot)||active.filter(x=>!x.time)[i];return `<div class="time-row"><span>${formatTime(slot)}</span>${t?`<div class="time-task"><input class="check" type="checkbox" data-toggle="${t.id}"><div><strong>${t.title}</strong><small>${t.estimate} min · ${t.category}</small></div></div>`:'<div class="time-task empty">Open focus time</div>'}</div>`}).join('')}
function renderCalendar(){let year=displayDate.getFullYear(),month=displayDate.getMonth();$('#calendarHeading').textContent=displayDate.toLocaleDateString(undefined,{month:'long',year:'numeric'});let first=new Date(year,month,1),start=new Date(year,month,1-first.getDay()), html='';for(let i=0;i<42;i++){let d=new Date(+start+i*86400000),key=iso(d),dayTasks=tasks.filter(t=>t.date===key&&!t.done);html+=`<div class="calendar-day ${d.getMonth()!==month?'other':''} ${key===iso(today)?'today':''}" data-dropdate="${key}"><div class="day-number">${d.getDate()}</div>${dayTasks.slice(0,3).map(t=>`<div draggable="true" data-drag="${t.id}" class="cal-task ${t.priority==='High'?'high':''}">${t.title}</div>`).join('')}${dayTasks.length>3?`<div class="cal-task">+${dayTasks.length-3} more</div>`:''}</div>`}$('#calendarGrid').innerHTML=html;let st=tasks.filter(t=>t.date===selectedDate);$('#selectedDayTitle').textContent=selectedDate===iso(today)?'Today':localDate(selectedDate).toLocaleDateString(undefined,{weekday:'long',month:'short',day:'numeric'});$('#selectedDayTasks').innerHTML=st.length?st.map(t=>`<div class="selected-task">${t.done?'✓ ':''}${t.title}</div>`).join(''):empty('Nothing planned yet.')}
function renderUpcoming(){let list=tasks.filter(t=>!t.done&&daysAway(t.date)>=0).sort(sortDate);$('#upcomingList').innerHTML=list.length?list.map(t=>{let d=localDate(t.date);return `<article class="upcoming-card ${daysAway(t.date)<=2?'urgent':''}"><div class="date-block"><b>${d.getDate()}</b><small>${d.toLocaleDateString(undefined,{month:'short'})}</small></div><div class="upcoming-main"><h3>${t.title}</h3><p>${t.category} · ${t.estimate} minutes${t.time?' · '+formatTime(t.time):''}</p></div><span class="pill ${t.priority}">${t.priority}</span><span class="countdown">${daysLabel(t.date)}</span><input class="check" type="checkbox" data-toggle="${t.id}"></article>`}).join(''):empty('No upcoming tasks yet.')}
function renderWeekly(){let start=new Date(today);start.setDate(today.getDate()-today.getDay()+1);$('#weeklyGrid').innerHTML=Array.from({length:7},(_,i)=>{let d=new Date(+start+i*86400000),key=iso(d),ts=tasks.filter(t=>t.date===key&&!t.done);return `<div class="week-day ${key===iso(today)?'today':''}"><span>${d.toLocaleDateString(undefined,{weekday:'short'})}</span><h3>${d.getDate()}</h3>${ts.map(t=>`<div class="week-task">${t.title}<br><small>${t.estimate} min</small></div>`).join('')||'<div class="empty">Open day</div>'}</div>`}).join('')}
function renderCompleted(){let list=tasks.filter(t=>t.done).sort((a,b)=>b.date.localeCompare(a.date));$('#completedList').innerHTML=list.length?list.map(taskHTML).join(''):empty('Complete a task to start your wins list.')}
function render(){renderDashboard();renderTasks();renderToday();renderCalendar();renderUpcoming();renderWeekly();renderCompleted()}
function toggle(id){let t=tasks.find(t=>t.id===id);t.done=!t.done;save();render();toast(t.done?'Task completed — nice work!':'Task moved back to your list.')}
function toast(msg){let el=$('#toast');el.textContent=msg;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2800)}
function openModal(id){$(id).classList.add('show')}function closeModals(){$$('.modal-backdrop').forEach(x=>x.classList.remove('show'))}
$$('[id^="openTaskModal"],#quickAddToday,#addOnSelected').forEach(b=>b.addEventListener('click',()=>{ $('#taskForm').elements.date.value=b.id==='addOnSelected'?selectedDate:iso(today);openModal('#taskModal')}));$('#openSmartModal').onclick=()=>{ $('#smartForm').elements.dueDate.value=iso(new Date(+today+4*86400000));openModal('#smartModal')};$$('.close-modal').forEach(b=>b.onclick=closeModals);$$('.modal-backdrop').forEach(x=>x.addEventListener('click',e=>{if(e.target===x)closeModals()}));
$('#taskForm').addEventListener('submit',e=>{e.preventDefault();let f=new FormData(e.target), data=Object.fromEntries(f);tasks.push({id:crypto.randomUUID(),title:data.title,notes:data.notes,date:data.date,time:data.time,priority:data.priority,category:data.category,estimate:+data.estimate,reminder:data.reminder,recurring:f.get('recurring')==='on',done:false});save();render();closeModals();e.target.reset();toast('Task added to your planner.');});
$('#smartForm').addEventListener('submit',e=>{e.preventDefault();let d=Object.fromEntries(new FormData(e.target)),due=localDate(d.dueDate),steps=+d.steps, names=['Choose a topic & gather requirements','Research and collect sources','Write the first draft','Edit and refine','Final review & submit'];for(let i=0;i<steps;i++){let date=new Date(+due-(steps-1-i)*86400000);tasks.push({id:crypto.randomUUID(),title:`${d.assignment}: ${names[i]}`,notes:`Smart plan for ${d.assignment}`,date:iso(date),time:'',priority:i===steps-1?'High':'Medium',category:'School',estimate:60,done:false})}save();render();closeModals();toast(`Your ${steps}-step plan is ready!`);e.target.reset()});
document.addEventListener('change',e=>{if(e.target.dataset.toggle)toggle(e.target.dataset.toggle)});document.addEventListener('click',e=>{let d=e.target.dataset.delete;if(d){tasks=tasks.filter(t=>t.id!==d);save();render();toast('Task removed.')}});['#taskSearch','#priorityFilter','#categoryFilter','#statusFilter'].forEach(s=>$(s).addEventListener('input',renderTasks));$('#searchInput').addEventListener('input',e=>{$('#taskSearch').value=e.target.value;renderTasks();if(e.target.value){location.hash='tasks';showView('tasks')}});
function showView(v){$$('.view').forEach(x=>x.classList.toggle('active',x.id===v));$$('.nav-item').forEach(x=>x.classList.toggle('active',x.dataset.view===v));window.scrollTo(0,0)}$$('[data-view]').forEach(a=>a.addEventListener('click',()=>showView(a.dataset.view)));window.addEventListener('hashchange',()=>showView(location.hash.slice(1)||'dashboard'));$('#menuToggle').onclick=()=>$('.sidebar').classList.toggle('open');
$('#prevMonth').onclick=()=>{displayDate.setMonth(displayDate.getMonth()-1);renderCalendar()};$('#nextMonth').onclick=()=>{displayDate.setMonth(displayDate.getMonth()+1);renderCalendar()};$('#goToday').onclick=()=>{displayDate=new Date(today);selectedDate=iso(today);renderCalendar()};$$('[data-calview]').forEach(b=>b.onclick=()=>{$$('[data-calview]').forEach(x=>x.classList.toggle('active',x===b));toast(`${b.textContent} view is selected`)});
document.addEventListener('dragstart',e=>{if(e.target.dataset.drag)e.dataTransfer.setData('task',e.target.dataset.drag)});document.addEventListener('dragover',e=>{if(e.target.closest('[data-dropdate]'))e.preventDefault()});document.addEventListener('drop',e=>{let day=e.target.closest('[data-dropdate]'),id=e.dataTransfer.getData('task');if(day&&id){let t=tasks.find(x=>x.id===id);t.date=day.dataset.dropdate;selectedDate=t.date;save();render();toast('Task rescheduled.')}});$('#notificationButton').onclick=()=>{let due=tasks.filter(t=>!t.done&&daysAway(t.date)<=1),message=due.length?`${due.length} task${due.length>1?'s':''} needs attention soon.`:'You’re all caught up!';toast(message);if('Notification'in window&&Notification.permission==='default')Notification.requestPermission();if('Notification'in window&&Notification.permission==='granted'&&due.length)new Notification('FocusFlow reminder',{body:message})};
$('#todayDate').textContent=today.toLocaleDateString(undefined,{weekday:'long',month:'long',day:'numeric'}).toUpperCase();render();if(location.hash)showView(location.hash.slice(1));
